import Head from 'next/head'
import Image from 'next/image'
import { HiMagnifyingGlass } from "react-icons/hi2";
import { useEffect, useState } from 'react'
import { ICountry } from '@/utils/ICountry'
import Link from 'next/link'
import {
  BodySection,
  CardStyle,
  Controller,
  CountrySection,
  CountryNameText,
  DivInput,
  DivText,
  DivText2,
  Input,
  Select,
} from 'styles.css';
import { Request } from '@/utils/Request';
import { useRecoilState, useRecoilValue } from 'recoil'
import { countryAtom, DarkModeAtom } from '@/utils/Atom';
import { Navbar } from '@/components/Navbar';


export default function Home() {

  const [Country, setCountry] = useRecoilState<ICountry[]>(countryAtom)
  const [CountryName, setCountryName] = useState('')
  const [CountryFilter, setCountryFilter] = useState('All')
  const DarkMode = useRecoilValue(DarkModeAtom)

  useEffect(() => {
    const reposta = Request(CountryName, CountryFilter)
    reposta.then(res => setCountry(res))

  }, [CountryName, CountryFilter])




  return (
    <>
      <Head>
        <title>Country</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className={BodySection}>
          <div className={Controller}>
            <div className={DivInput}>
              <HiMagnifyingGlass className='svg' />
              <input
                className={Input}
                type='text'
                placeholder='Search for a country...'
                onChange={e => setCountryName(e.target.value)}
              />
            </div>
            <select className={Select} onChange={(e) => setCountryFilter(e.target.value)}>
              <option>All</option>
              <option>Africa</option>
              <option>South America</option>
              <option>North America</option>
              <option>Asia</option>
              <option>Europe</option>
              <option>Oceania</option>
            </select>
          </div>
          <section className={CountrySection}>
            {Country?.map(item => (
              <div className={CardStyle} key={item.name.common}>
                <Link href={`/Country/${item.name.common}`} >
                  <Image src={item.flags.svg} width={300} height={200} alt='A country flag' />
                  <div className={DivText}>
                    <h2 className={CountryNameText}>{item.name.common}</h2>
                  </div>
                  <div className={DivText2}>
                    <h3>Population: {Intl.NumberFormat().format(item.population)}</h3>
                    <h3>Region: {item.continents}</h3>
                    <h3>Capital: {item.capital}</h3>
                  </div>
                </Link>
              </div>
            ))}
          </section>
        </section>
      </main>
    </>
  )
}
