import { Navbar } from '@/components/Navbar'
import { countryAtom, DarkModeAtom } from '@/utils/Atom'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { AiOutlineArrowLeft } from 'react-icons/ai'
import { useRecoilValue } from 'recoil'
import {
  BackButton,
  ButtonText,
  CountryInfo,
  CountryInfoBlack,
  CountryInfoText,
  Div1,
  Flex,
  Flex2,
  InfoSection,
  InfoSectionCountryName,
  Titulo
}
  from 'styles.css'

const Country = () => {
  const router = useRouter()
  const { id } = router.query

  const lista = useRecoilValue(countryAtom)
  const listaFiltrada = lista.filter(item => item.name.common === id)
  const DarkMode = useRecoilValue(DarkModeAtom)


  function SpreadObject(ref: object) {
    let arr = []
    for (const [key, value] of Object.entries(ref)) {
      arr.push(value)
    }
    return arr.slice(0, 3)
  }

  function VerifyList(index: number, lastIndex: number, text: string) {
    let sign = index == lastIndex ? '.' : ','
    return <p key={index} > {text}{sign}</p>
  }


  return (
    <>
      <Head>
        <title>Country Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={DarkMode ? CountryInfoBlack : CountryInfo}>
        <Link href='/' className={BackButton}>
          <AiOutlineArrowLeft className='svg' />
          <h4 className={ButtonText}>Back</h4>
        </Link>
        {listaFiltrada.map(item => (
          <section key={item.name.common} className={InfoSection}>
            <Image src={item.flags.svg} width={700} height={500} alt='Country Flag' />
            <article className={CountryInfoText}>
              <h3 className={InfoSectionCountryName}>{item.name.common}</h3>
              <div className={Flex2}>
                <div className={Div1}>
                  <p><span className={Titulo}>Official Name:</span> {item.name.official}</p>
                  <p><span className={Titulo}>Population: </span> {Intl.NumberFormat().format(item.population)} </p>
                  <p><span className={Titulo}>Region:</span> {item.continents}</p>
                  <p><span className={Titulo}>SubRegion:</span> {item.subregion}</p>
                </div>
                <div className={Div1}>
                  <div className={Flex}>
                    <p className={Titulo}>Capital:</p>
                    {SpreadObject(item.capital).map((capital, index) => (
                      VerifyList(index, SpreadObject(item.capital).length - 1, capital)
                    ))}
                  </div>
                  <div className={Flex}>
                    <p className={Titulo}>Languages:</p>
                    {SpreadObject(item.languages).map((language, index) => (
                      VerifyList(index, SpreadObject(item.languages).length - 1, language)
                    ))}
                  </div>
                  <div className={Flex}>
                    <p className={Titulo}>Currencies:</p>
                    {SpreadObject(item.currencies).map((currencie, index) => (
                      VerifyList(index, SpreadObject(item.languages).length - 1, currencie.name)
                    ))}
                  </div>
                  <div className={Flex}>
                    <p><span className={Titulo}>Timezone:</span> </p>
                    {item.timezones.slice(0, 3).map((timezone, index) => (
                      VerifyList(index, item.timezones.length - 1, timezone)
                    ))}
                  </div>
                </div>
              </div>
            </article>
          </section>
        ))}
      </section>
    </>
  )
}

export default Country